/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medical;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Personal
 */
public class Final extends javax.swing.JFrame {
String user,field;
int docid;
    /**
     * Creates new form Final
     */
    public Final() {
        
        initComponents();
        
    }
    
  
    
    public Final(String userid,int doc,String s){
        
       
        initComponents();
        
         user=userid;
         field=s;
        docid=doc;
         jLabel28.setText(user);
         try{
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/medical","root","1997");
             Statement st=conn.createStatement(); 
              CallableStatement cst=conn.prepareCall("{call appid("+user+","+docid+")}");
              ResultSet rs=cst.executeQuery();
              
             
              while(rs.next())
              {     
                  jLabel15.setText(rs.getString(1));
                  jLabel16.setText(rs.getString(2));
                  jLabel17.setText(rs.getString(3));
                  jLabel18.setText(rs.getString(4));
                  jLabel19.setText(rs.getString(5));
                  jLabel20.setText(rs.getString(6));
                  jLabel21.setText(rs.getString(7));
                  jLabel22.setText(rs.getString(8));
                  jLabel23.setText(rs.getString(9));
                  jLabel24.setText(rs.getString(10));
                  jLabel25.setText(rs.getString(11));
                  jLabel27.setText(rs.getString(12));
                  jLabel29.setText(rs.getString(13));
                  jLabel30.setText(rs.getString(14));
              }
              
              
              
             
         }   
              
              
           
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(607, 416));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Your Booking is Confirmed.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 0, 210, 20);

        jLabel2.setText("USER ID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 70, 100, 14);

        jLabel3.setText("NAME:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 100, 70, 20);

        jLabel4.setText("GENDER:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(29, 120, 90, 20);

        jLabel5.setText("DOB:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 140, 80, 20);

        jLabel6.setText("Your Details are:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(29, 40, 130, 14);

        jLabel7.setText("Your Appointment Details are:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(29, 192, 200, 14);

        jLabel8.setText("DOC ID:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(29, 212, 140, 14);

        jLabel9.setText("DOC NAME:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(29, 232, 140, 14);

        jLabel10.setText("DOC PHONE:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(29, 252, 140, 14);

        jLabel11.setText("DOC FIELD:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(29, 292, 130, 14);

        jLabel12.setText("DATE OF APPOINTMENT:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(29, 312, 170, 14);

        jLabel13.setText("SCHEDULED APPOINTMENT TIME:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 330, 230, 20);

        jLabel14.setText("PHONE:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(29, 162, 80, 20);

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(360, 370, 110, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(280, 60, 124, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(280, 100, 100, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(370, 100, 60, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(280, 120, 140, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(280, 140, 130, 20);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(280, 160, 133, 20);
        getContentPane().add(jLabel21);
        jLabel21.setBounds(310, 210, 150, 20);
        getContentPane().add(jLabel22);
        jLabel22.setBounds(310, 230, 121, 20);
        getContentPane().add(jLabel23);
        jLabel23.setBounds(310, 250, 150, 20);
        getContentPane().add(jLabel24);
        jLabel24.setBounds(380, 270, 180, 20);
        getContentPane().add(jLabel25);
        jLabel25.setBounds(370, 290, 140, 20);

        jLabel26.setText("DOC ADDRESS:");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(29, 272, 150, 14);
        getContentPane().add(jLabel27);
        jLabel27.setBounds(370, 310, 130, 20);
        getContentPane().add(jLabel28);
        jLabel28.setBounds(344, 11, 69, 14);
        getContentPane().add(jLabel29);
        jLabel29.setBounds(360, 330, 85, 20);
        getContentPane().add(jLabel30);
        jLabel30.setBounds(440, 330, 70, 20);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 370, 90, 30);

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medical/resources/concept-appointment.jpg"))); // NOI18N
        jLabel31.setOpaque(true);
        getContentPane().add(jLabel31);
        jLabel31.setBounds(-120, 0, 760, 420);

        setSize(new java.awt.Dimension(623, 455));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     try{
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/medical","root","1997");
             Statement st=conn.createStatement(); 
               String delete="delete from appointments where userid='"+user+"' and docid='"+docid+"';" ;
             st.executeUpdate(delete);
              this.setVisible(false);
             new Appoint(docid,user,field).setVisible(true);
              
             
         }   
              
              
           
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.setVisible(false);
        new Confirmpage(user).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Final().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
